[package]
name = "url-shortener-api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.4"
mysql = "26.0.0"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"